#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/dcon
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver

spring:
  datasource:
    url: jdbc:mysql://kukusdb.capuaxnohbhe.us-west-1.rds.amazonaws.com:3306/kencor_db?useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: Th1$Is53cure!
